openapi: 3.0.0
info:
  title: URL Shortener
  description: URL Shortener Demo
  version: 1.0.0
servers:
  - url: http://localhost:3140/v1/api
    description: Local server for testing

components:
  securitySchemes:
    Bearer:
      type: apiKey
      scheme: apiKey
      name: X-Authorization
      in: header
      description: >
        Note: Login to get your JWT token first, then enter "Bearer <JWT Token>" below, e.g., Bearer 123456abcdef.

paths:
  /auth/signup:
    post:
      tags:
        - Auth
      summary: User signup
      description: User registration endpoint
      parameters:
        - in: header
          name: version
          schema:
            type: string
            default: "1.0.0"
          required: true
        - in: header
          name: Accept-Language
          schema:
            type: string
            default: en
          required: true
        - in: header
          name: time-zone
          schema:
            type: string
            default: Asia/Calcutta
          required: true
        - in: header
          name: device-type
          schema:
            type: string
            default: android
          required: true
        - in: header
          name: device-token
          schema:
            type: string
            default: "12345"
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                confirmPassword:
                  type: string
                houseNumber:
                  type: string
                roadNumber:
                  type: string
                address:
                  type: string
                latitude:
                  type: number
                longitude:
                  type: number
                addressType:
                  type: string
              example:
                name: test
                email: testkr11@yopmail.com
                password: "Test@12345"
                confirmPassword: "Test@12345"
                houseNumber: "11"
                roadNumber: "12"
                address: Janjeerwala Square
                latitude: 0.0
                longitude: 0.0
                addressType: Home
      responses:
        "200":
          description: OTP sent to the registered email
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: OTP sent to your registered email
        "500":
          description: Signup failed

  /shorten:
    post:
      tags:
        - Shorten
      summary: Shorten URL
      description: Endpoint to shorten URLs
      security:
        - Bearer: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                longUrl:
                  type: string
                  format: uri
                alias:
                  type: string
                topic:
                  type: string
              example:
                longUrl: "http://www.example.com"
                alias: "Test"
                topic: "Test"
      responses:
        "200":
          description: Successfully shortened URL
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      shortUrl:
                        type: string
                example:
                  message: Success
                  data:
                    shortUrl: "http://localhost:4321/v1/user/shorten/5f3b1"
        "500":
          description: Internal server error

  /shorten/{alias}:
    get:
      tags:
        - Shorten
      summary: Get Shorten URL By Alias
      description: Endpoint to get shorten URLs
      security:
        - Bearer: []
      parameters:
        - in: path
          name: alias
          schema:
            type: string
            required: true
      responses:
        "200":
          description: Successfully shortened URL
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      shortUrl:
                        type: string
                example:
                  message: Success
                  data:
                    shortUrl: "http://localhost:4321/v1/user/shorten/5f3b1"
        "500":
          description: Internal server error
  /analytics/overall:
    get:
      tags:
        - Shorten
      summary: Get Overall Shorten URL 
      description: Endpoint to get overall shorten URLs analysis
      security:
        - Bearer: []
      responses:
        "200":
          description: Successfully shortened URL
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      shortUrl:
                        type: string
                example:
                  message: Success
                  data:
                    shortUrl: "http://localhost:4321/v1/user/shorten/5f3b1"
        "500":
          description: Internal server error
  /analytics/{alias}:
    get:
      tags:
        - Shorten
      summary: Get Analytics Shorten URL By Alias
      description: Endpoint to get shorten URLs analysis by alias
      security:
        - Bearer: []
      parameters:
        - in: path
          name: alias
          schema:
            type: string
            required: true
      responses:
        "200":
          description: Successfully shortened URL
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      shortUrl:
                        type: string
                example:
                  message: Success
                  data:
                    shortUrl: "http://localhost:4321/v1/user/shorten/5f3b1"
        "500":
          description: Internal server error
  /analytics/topic/{topic}:
    get:
      tags:
        - Shorten
      summary: Get Analytics Shorten URL By topic
      description: Endpoint to get shorten URLs analysis by topic
      security:
        - Bearer: []
      parameters:
        - in: path
          name: topic
          schema:
            type: string
            required: true
      responses:
        "200":
          description: Successfully shortened URL
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      shortUrl:
                        type: string
                example:
                  message: Success
                  data:
                    shortUrl: "http://localhost:4321/v1/user/shorten/5f3b1"
        "500":
          description: Internal server error

